### ISSUE TITLE
python issue

### ISSUE THREAD

**Issue by lyoussar** [galaxyproject/galaxy#5530]
Hi!
After upgrading from ubuntu 17.04 to 17.10, galaxy local instance stopped to work fault of python version. 
Any idea how to fix this issue?

**Comment by nsoranzo** [comment]
You may try to remove the Galaxy virtualenv (by default the `.venv` subdir of your galaxy dir) and restart Galaxy. Also, can you provide the exact error?

**Comment by lyoussar** [comment]
Sure:
sh run.sh
Activating virtualenv at .venv
Traceback (most recent call last):
  File "/home/loubna/galaxy/.venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/loubna/galaxy/.venv/local/lib/python2.7/site-packages/pip/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

**Comment by lyoussar** [comment]
Gracias Maestro! My galaxy works like a charm after removing .venv. The re-installation was fluent through miniconda. Thanks again!

**Comment by pvanheus** [comment]
Just adding a note to this closed issue - since it still shows up on Google results. This error can be caused by having a different Python on the Galaxy server to the one on cluster compute nodes. In this case a solution might be installing a virtualenv using one of the compute nodes and referring to it in `job_conf.xml` using the `<env>` tag as documented in the Galaxy Admin docs on [framework dependencies](https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html).
