### ISSUE TITLE
Diffbind 2.2.0 has dependency issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2318]
Original problem "Diffbind 2.1.0 produces green empty datasets with dependency issues at http://usegalaxy.org". See below for v 2.2.0 issue after update to 2.2.0.

**Error**

> WARNING: ignoring environment value of R_HOME
> [1] "en_US.UTF-8"
> Loading required package: GenomicRanges
> Loading required package: methods
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: 'BiocGenerics'

**Reported at Galaxy Biostars, confirmed on Main**
https://biostar.usegalaxy.org/p/17453/
https://biostar.usegalaxy.org/p/17458/

**Update 7/20/16**

Tools still has issues and will produce a true error dataset now. 

> job stderr:
> Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
> Error in library("DiffBind") : there is no package called 'DiffBind'
> 
> job stdout:
> WARNING: ignoring environment value of R_HOME
> [1] "en_US.UTF-8"

**Comment by jennaj** [comment]
Update 10-14: Tool still has dependency issues

**Comment by jennaj** [comment]
@galaxyproject/guac This tool still has issues. Has been a problem since May - would someone have time to look into it? thanks!

**Comment by martenson** [comment]
The error for the diffbind dependency seems to be as follows:

```
* installing *source* package ‘Rsamtools’ ...
** libs
In file included from samtools/bam.h:52,
                 from samtools/sam.h:4,
                 from bamfile.h:5,
                 from R_init_Rsamtools.c:4:
samtools/bgzf.h:33:18: error: zlib.h: No such file or directory
make: *** [R_init_Rsamtools.o] Error 1
ERROR: compilation failed for package ‘Rsamtools’
* removing ‘/cvmfs/main.galaxyproject.org/deps/diffbind/1.8.3/bgruening/diffbind/d6dcb3dd5f8f/Rsamtools’
```

looking into it

**Comment by jennaj** [comment]
@galaxyproject/guac @martenson  Update - still an issue

**Comment by jennaj** [comment]
Is there an update about when the tool will be fixed? Thanks!

**Comment by bgruening** [comment]
We have a conda package now. Still the tool needs to be updated.

**Comment by jennaj** [comment]
@davebx Could we update this on Main soon? Thanks!

**Comment by davebx** [comment]
@jennaj I'll need @bgruening to update it in MTS first.

**Comment by davebx** [comment]
I've installed diffbind 2.2.0 on main.

**Comment by jennaj** [comment]
Testing

**Comment by jennaj** [comment]
Failed with updated version 2.2.0

**Tool ID**	toolshed.g2.bx.psu.edu/repos/bgruening/diffbind/diffbind/2.2.0

**Error**

```
Command Line

ln -s /galaxy-repl/main/files/X/X/dataset_19739448.dat 1_bamreads.bam && ln -s /galaxy-repl/main/files/_metadata_files/X/X/metadata_1379529.dat 1_bamreads.bai && ln -s /galaxy-repl/main/files/X/X/dataset_19739447.dat 1_bamcontrol.bam && ln -s /galaxy-repl/main/files/_metadata_files/X/X/metadata_1379530.dat 1_bamcontrol.bai && ln -s /galaxy-repl/main/files/X/X/dataset_19739444.dat 2_bamreads.bam && ln -s /galaxy-repl/main/files/_metadata_files/X/379/metadata_1379523.dat 2_bamreads.bai && ln -s /galaxy-repl/main/files/X/X/dataset_19739443.dat 2_bamcontrol.bam && ln -s /galaxy-repl/main/files/_metadata_files/001/379/metadata_1379527.dat 2_bamcontrol.bai &&  Rscript /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/diffbind/69138bfd8644/diffbind/diffbind.R -i /galaxy-repl/main/jobdir/015/707/15707644/tmpoWdRNj -o /galaxy-repl/main/files/X/X/dataset_19761704.dat -p /galaxy-re
 pl/main/files/X/X/dataset_19761705.dat -f bed

stderr

Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
Error in library("getopt") : there is no package called 'getopt'

stdout

[1] "en_US.UTF-8"
```

**Side note:** notice the two spelling errors in the stderr. "occured" & "intput"

**Comment by gregvonkuster** [comment]
This may be related to this https://github.com/galaxyproject/galaxy/issues/4032, but not sure.  The diffbind tool does not produce a dataset collection on output, but the empty green datasets produced on output is the same behavior I am seeing with tools that produce dataset collections that should be red and empty instead of green and empty.

**Comment by jennaj** [comment]
Thanks @gregvonkuster There were a few recent reports of this plus my own testing. I'll recheck inputs again and write back. Definitely agree empty results could be captured/reported to the user better.

@davebx What do you think? "Dependency issue" or "empty result not captured"?

**Comment by davebx** [comment]
@jennaj Can confirm dependency issue. Looking into it.

**Comment by davebx** [comment]
@jennaj this should be resolved with wrapper version 2.2.1

**Comment by jennaj** [comment]
Resolved, thanks @davebx
