### ISSUE TITLE
Workflow runs that use collection lists are broken

### ISSUE THREAD

**Issue by ghost** [galaxyproject/galaxy#1946]
**Reported against commit 29b6d54.**

**When running a workflow that uses collection lists as parameters, the workflow fails to run with the server reporting:**

```
galaxy.workflow.run ERROR 2016-03-17 15:56:38,210 Failed to schedule Workflow[id=6,name= pipeline (imported from uploaded file)], problem occurred on WorkflowStep[index=0,type=data_input].                                                                                                                             
Traceback (most recent call last):                                                                                                                            
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke                                                            
    jobs = self._invoke_step( step )                                                                                                                          
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step                                                      
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )                                                                   
  File "/c8000xd3/galaxy/lib/galaxy/workflow/modules.py", line 487, in execute                                                       
    content_type = input_dataset_hda.history_content_type                                                                                                     
AttributeError: 'list' object has no attribute 'history_content_type'                                                                                         
galaxy.workflow.run ERROR 2016-03-17 15:56:38,324 Failed to execute scheduled workflow.                                                                       
Traceback (most recent call last):                                                                                                                            
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke                                                           
    outputs = invoker.invoke()                                                                                                                                
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke                                                            
    jobs = self._invoke_step( step )                                                                                                                          
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step                                                      
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )                                                                   
  File "/c8000xd3/galaxy/lib/galaxy/workflow/modules.py", line 487, in execute                                                       
    content_type = input_dataset_hda.history_content_type                                                                                                     
AttributeError: 'list' object has no attribute 'history_content_type' 
```

**I've git-bisected this to be caused by the following commit:**

```
40c9e1af255b548c35a9d98ac4c196058d185541 is the first bad commit                                                                                              
commit 40c9e1af255b548c35a9d98ac4c196058d185541                                                                                                               
Author: guerler <aysam.guerler@gmail.com>                                                                                                                     
Date:   Wed Mar 9 10:33:42 2016 -0500                                                                                                                         

    Use value_to_basic and to_json when populating the tool model 
```

**Bisect log:**

```

git bisect start                                                                                                                                              
# good: [d6e38c7d482eae65fc135cd65a13b7f215220cd5] remove unused import                                                                                       
git bisect good d6e38c7d482eae65fc135cd65a13b7f215220cd5                                                                                                      
# bad: [29b6d545cf229518840e29d7468d65e4221db95a] Merge pull request #1926 from blankenberg/iobio-display                                                     
git bisect bad 29b6d545cf229518840e29d7468d65e4221db95a                                                                                                       
# good: [1e46198becdba27f98f7ce93bb27f21ae59392a1] Merge pull request #1602 from carlfeberhard/history.contents                                               
git bisect good 1e46198becdba27f98f7ce93bb27f21ae59392a1                                                                                                      
# good: [78b1f9af3741889a542d881cf242a12acc932a7e] Dockerfile testing improvements.                                                                           
git bisect good 78b1f9af3741889a542d881cf242a12acc932a7e                                                                                                      
# skip: [4cf90643580c4cda20b2076e9ebe2bb5660a4c75] Merge, rebuild client.                                                                                     
git bisect skip 4cf90643580c4cda20b2076e9ebe2bb5660a4c75                                                                                                      
# skip: [370ea10f75196e899868a248b1f301d4994debd8] Use real routes for tours, and make them actually work.  Now it's possible to open the tour index in a new tab, etc., instead of just using javascript craziness.                                                                                                        
git bisect skip 370ea10f75196e899868a248b1f301d4994debd8                                                                                                      
# skip: [8d71c3dc1b7ed1ad33f60af1f1fe71e4c7ece108] Change to sentry middleware to work with modern raven clients.  This allows us to upgrade raven and actually show the entire event_id to users on the guru meditation page.                                                                                              
git bisect skip 8d71c3dc1b7ed1ad33f60af1f1fe71e4c7ece108                                                                                                      
# good: [158732edb6ceb1ed073d058b3a71c4c26e4887d2] Merge pull request #1835 from jmchilton/from_editor_fix                                                    
git bisect good 158732edb6ceb1ed073d058b3a71c4c26e4887d2                                                                                                      
# skip: [773095d403929ad7f44561ff17f960f088f1b9ce] Unify json representation for regular datasets and collections                                             
git bisect skip 773095d403929ad7f44561ff17f960f088f1b9ce                                                                                                      
# good: [7955a2b769d02e57ed609b636621cd76d27bc3a8] Update run.mako                                                                                            
git bisect good 7955a2b769d02e57ed609b636621cd76d27bc3a8                                                                                                      
# good: [1aaf65e8b6306e3d4a7e69d545d9fe300c1510ca] missing ;; in case stop                                                                                    
git bisect good 1aaf65e8b6306e3d4a7e69d545d9fe300c1510ca                                                                                                      
# bad: [915993bbd8f82afef9b68f5d8820437a07f6f264] Add display_applications/iobio/vcf.xml.                                                                     
git bisect bad 915993bbd8f82afef9b68f5d8820437a07f6f264                                                                                                       
# bad: [79a0972675a3594292c7e28e36639d67d49863ad] Improve empty dataset check, handle from_json inconsistency                                                 
git bisect bad 79a0972675a3594292c7e28e36639d67d49863ad                                                                                                       
# bad: [b1a9823a3c596a303973b8e1dbbd734a67c392ef] Remove RuntimeValue arrays                                                                                  
git bisect bad b1a9823a3c596a303973b8e1dbbd734a67c392ef                                                                                                       
# bad: [40c9e1af255b548c35a9d98ac4c196058d185541] Use value_to_basic and to_json when populating the tool model                                               
git bisect bad 40c9e1af255b548c35a9d98ac4c196058d185541                                                                                                       
# good: [14d6e34e010cafd98d8db2680c4c339e727c968d] Rename from_html to from_json                                                                              
git bisect good 14d6e34e010cafd98d8db2680c4c339e727c968d                              


```

**Comment by ghost** [comment]
Pinging @guerler. Could you take a look at this one please?

**Comment by guerler** [comment]
Yes.

**Comment by jmchilton** [comment]
Was this run against the API or using the GUI?

**Comment by ghost** [comment]
GUI. Nothing of note was displayed on the GUI, just an empty workflow is created.

**Comment by guerler** [comment]
I will try to reproduce this by creating the same workflow. Please let me know which workflow nodes the workflow contains.

**Comment by ghost** [comment]
While trying to recreate a smaller workflow, I encountered a similar bug which bisected to the same revision (40c9e1af255b). The 'kcolumn' tool from https://github.com/einon/galaxy-tools/tree/master/penncnv uses the following to collect output datasets:

```
<collection type="list" name="splitout" label="split-files">
            <discover_datasets pattern="__name__" directory="outputs"/>
</collection>
```

Which triggers this latest bug when run as a workflow. I've attached a small workflow which does this, the input file is not important as it doesn't get opened before the bug occurs. The trace produced for this is:

```
StatementError: (exceptions.TypeError) <galaxy.model.HistoryDatasetAssociation object at 0x7f3b2f27f290> is not JSON serializable [SQL: u'INSERT INTO workflow_request_input_step_parameter (workflow_invoc
ation_id, workflow_step_id, parameter_value) VALUES (%(workflow_invocation_id)s, %(workflow_step_id)s, %(parameter_value)s) RETURNING workflow_request_input_step_parameter.id'] [parameters: [{'workflow_s
tep_id': 1, 'workflow_invocation_id': 1, 'parameter_value': [<galaxy.model.HistoryDatasetAssociation object at 0x7f3b2f27f290>]}]]
galaxy.workflow.run DEBUG 2016-03-21 15:54:16,848 Workflow step 1 of invocation 1 invoked (0.241 ms)
galaxy.tools ERROR 2016-03-21 15:54:16,867 Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/__init__.py", line 1138, in handle_single_execution
    job, out_data = self.execute( trans, incoming=params, history=history, rerun_remap_job_id=rerun_remap_job_id, mapping_over_collection=mapping_over_collection, execution_cache=execution_cache )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/__init__.py", line 1216, in execute
    return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/actions/__init__.py", line 425, in execute
    hdca_name = self.get_output_name( output, None, tool, on_text, trans, incoming, history, wrapped_params.params, job_params )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/parameters/wrapped.py", line 33, in params
    self.wrap_values( self.tool.inputs, params, skip_missing_values=not self.tool.check_values )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/parameters/wrapped.py", line 71, in wrap_values
    name=input.name )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/tools/wrappers.py", line 216, in __init__
    self.metadata = self.MetadataWrapper( dataset.metadata )
AttributeError: 'list' object has no attribute 'metadata'
galaxy.tools.execute WARNING 2016-03-21 15:54:16,867 There was a failure executing a job for tool [kcolumn] - Error executing tool: 'list' object has no attribute 'metadata'
galaxy.tools.execute DEBUG 2016-03-21 15:54:16,867 Executed 1 job(s) for tool kcolumn request: (18.734 ms)
galaxy.workflow.run ERROR 2016-03-21 15:54:16,873 Failed to schedule Workflow[id=1,name=Unnamed workflow (imported from uploaded file)], problem occurred on WorkflowStep[index=1,type=tool].
Traceback (most recent call last):
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/modules.py", line 1095, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
galaxy.workflow.run ERROR 2016-03-21 15:54:16,874 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/modules.py", line 1095, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
galaxy.workflow.scheduling_manager ERROR 2016-03-21 15:54:16,877 Exception raised while attempting to schedule workflow request.
Traceback (most recent call last):
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/scheduling_manager.py", line 177, in __attempt_schedule
    workflow_scheduler.schedule( workflow_invocation )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/schedulers/core.py", line 43, in schedule
    workflow_invocation=workflow_invocation,
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 27, in schedule
    return __invoke( trans, workflow, workflow_run_config, workflow_invocation )
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/workflow/run.py", line 103, in __invoke
    trans.sa_session.flush()
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 781, in _emit_insert_statements
    execute(statement, params)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 598, in _init_compiled
    for key in compiled_params
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 598, in <genexpr>
    for key in compiled_params
  File "/home/mark/source/galaxy-test/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 958, in process
    return impl_processor(process_param(value, dialect))
  File "/home/mark/source/galaxy-test/galaxy/lib/galaxy/model/custom_types.py", line 55, in process_bind_param
    value = json_encoder.encode(value)
  File "/usr/lib64/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib64/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib64/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

Workflow file:

```
{
    "a_galaxy_workflow": "true", 
    "annotation": "", 
    "format-version": "0.1", 
    "name": "Unnamed workflow", 
    "steps": {
        "0": {
            "annotation": "", 
            "content_id": null, 
            "id": 0, 
            "input_connections": {}, 
            "inputs": [
                {
                    "description": "", 
                    "name": "Input Dataset"
                }
            ], 
            "label": null, 
            "name": "Input dataset", 
            "outputs": [], 
            "position": {
                "left": 271.5, 
                "top": 257
            }, 
            "tool_errors": null, 
            "tool_id": null, 
            "tool_state": "{\"name\": \"Input Dataset\"}", 
            "tool_version": null, 
            "type": "data_input", 
            "uuid": "dd182573-93ee-4f3f-8cd3-db2c6f9d5b5b", 
            "workflow_outputs": []
        }, 
        "1": {
            "annotation": "", 
            "content_id": "kcolumn", 
            "id": 1, 
            "input_connections": {
                "inputfile": {
                    "id": 0, 
                    "output_name": "output"
                }
            }, 
            "inputs": [
                {
                    "description": "runtime parameter for tool Column Extraction", 
                    "name": "inputfile"
                }
            ], 
            "label": null, 
            "name": "Column Extraction", 
            "outputs": [
                {
                    "name": "splitout", 
                    "type": "input"
                }, 
                {
                    "name": "output", 
                    "type": "txt"
                }
            ], 
            "position": {
                "left": 594.5, 
                "top": 336
            }, 
            "post_job_actions": {}, 
            "tool_errors": null, 
            "tool_id": "kcolumn", 
            "tool_state": "{\"__page__\": 0, \"end\": \"\\\"1000\\\"\", \"name\": \"\\\"false\\\"\", \"__rerun_remap_job_id__\": null, \"operation_selection\": \"{\\\"cols_per_split\\\": \\\"3\\\", \\\"__current_case__\\\": 0, \\\"op\\\": \\\"split\\\"}\", \"start\": \"\\\"1\\\"\", \"tab\": \"\\\"false\\\"\", \"out\": \"\\\"tmp\\\"\", \"heading\": \"\\\"2\\\"\", \"inputfile\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\"}", 
            "tool_version": "0.1.0", 
            "type": "tool", 
            "uuid": "c7b8d15a-6d80-4b47-a0ba-c6c3ab47a02d", 
            "workflow_outputs": []
        }
    }, 
    "uuid": "e5d46af2-bf95-4686-8b3a-a18a50e16e58"
}
```

**Comment by guerler** [comment]
@jmchilton This might be related. I build a simple workflow in `909a549` containing the above `kcolumn` and an `addValue` module:

![workflow](https://cloud.githubusercontent.com/assets/2105447/14021116/78ef465e-f1b0-11e5-91f2-409bbeed9528.png)

It produces this error when executed:
`File "/Users/guerler/galaxy/lib/galaxy/tools/execute.py", line 84, in execute
execution_tracker.create_output_collections( trans, history, params )
UnboundLocalError: local variable 'params' referenced before assignment`

**Comment by martenson** [comment]
Not sure how much related but when I try to import that WF json code above I get 

```
Error - <type 'exceptions.ValueError'>: too many values to unpack
URL: http://127.0.0.1:8080/galaxy/workflow/import_workflow
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/base.py', line 131 in __call__
  return self.handle_request( environ, start_response )
File '/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/base.py', line 189 in handle_request
  body = method( trans, **kwargs )
File '/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 937 in import_workflow
  missing_tool_id, missing_tool_name, missing_tool_version = missing_tool_tup
ValueError: too many values to unpack
```

**Comment by guerler** [comment]
@jmchilton Thx for #2009, but re-running my example now produces:

 `File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 230, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/Users/guerler/galaxy/lib/galaxy/workflow/modules.py", line 1074, in execute
    workflow_invocation_uuid=invocation.uuid.hex
  File "/Users/guerler/galaxy/lib/galaxy/tools/execute.py", line 75, in execute
    params = param_combinations[0]
IndexError: list index out of range`

@martenson It works for me. I can import the workflow file in dev, and reproduce the error @einon described. Thx a lot for the excellent report on this.

**Comment by guerler** [comment]
I re-opened this issue since I can still reproduce the above `IndexError: list index out of range` for my example.

**Comment by guerler** [comment]
Closing in favor of #2084
