### PR TITLE
[17.01] Fix problem with cleaning up jobs in local runner.

### LINKED ISSUE #3801: [17.01] Base JobState class does not have .cleanup() method
This breaks when using the local runner:

```
galaxy.jobs.runners ERROR 2017-03-22 11:53:04,424 (1778) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "galaxy/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "galaxy/lib/galaxy/jobs/runners/local.py", line 133, in queue_job
    self._fail_job_local(job_wrapper, "Unable to finish job")
  File "galaxy/lib/galaxy/jobs/runners/local.py", line 173, in _fail_job_local
    self.fail_job(job_state, exception=True)
  File "galaxy/lib/galaxy/jobs/runners/__init__.py", line 381, in fail_job
    job_state.cleanup()
AttributeError: 'JobState' object has no attribute 'cleanup'
```

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes #3801 (broken in b78287f as part of #3291).

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

File: lib/galaxy/jobs/runners/__init__.py [hunk 1]
```diff
@@ -427,6 +429,19 @@ def default_job_file( files_dir, id_tag ):
     def default_exit_code_file( files_dir, id_tag ):
         return os.path.join( files_dir, 'galaxy_%s.ec' % id_tag )
 
+    def cleanup( self ):
+        for file in [ getattr( self, a ) for a in self.cleanup_file_attributes if hasattr( self, a ) ]:
```
Comment (nsoranzo) [inline lib/galaxy/jobs/runners/__init__.py:433]: Not needed for this PR, but it would be nice to use another variable name instead of `file` which is a standard library function in Python2.

Comment (jmchilton) [reply lib/galaxy/jobs/runners/__init__.py:433]: Agreed completely - next time I'm in there to clean up that TODO I added I'll try to remember to fix this as well.

**Comment by martenson** [comment]
@jmchilton after release for release branch new things please target the next milestone, se we have it in release notes somewhere
