### ISSUE TITLE
Regression in workflows with nested list mapping.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5146]
The test test_workflow_run_dynamic_output_collections_3 added with #2634 is not a great test - it failed to catch what I think is a regression in workflows with doubly nested lists that I think I introduced in #5013. 

```
AttributeError: 'CollectionTypeDescriptionFactory' object has no attribute 'for_type_description'
galaxy.workflow.run ERROR 2017-12-06 16:00:40,821 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/run.py", line 80, in __invoke
    outputs = invoker.invoke()
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/run.py", line 185, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/run.py", line 258, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans, self.progress, invocation_step)
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/modules.py", line 888, in execute
    job_callback=lambda job: self._handle_post_job_actions(step, job, invocation.replacement_dict),
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/execute.py", line 81, in execute
    execution_tracker.ensure_implicit_collections_populated(history, mapping_params.param_template)
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/execute.py", line 430, in ensure_implicit_collections_populated
    self.precreate_output_collections(history, params)
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/execute.py", line 276, in precreate_output_collections
    effective_structure = self._mapped_output_structure(trans, output)
  File "/Users/john/workspace/galaxy/lib/galaxy/tools/execute.py", line 244, in _mapped_output_structure
    output_structure = tool_output_to_structure(self.sliced_input_collection_type, tool_output, collections_manager)
  File "/Users/john/workspace/galaxy/lib/galaxy/dataset_collections/structure.py", line 185, in tool_output_to_structure
    tree = UnitializedTree(collection_type_descriptions.for_type_description("list"))  # list is obviously wrong...
AttributeError: 'CollectionTypeDescriptionFactory' object has no attribute 'for_type_description'
```

**Comment by martenson** [comment]
Is this 18.01-blocking? If not please change or drop the milestone.

**Comment by jmchilton** [comment]
It is blocking - but I'd say blocking release not branching. Issues block branching not PRs, I'll definitely get to this after the branch.

**Comment by martenson** [comment]
> Issues block branching not PRs 

I am a bit confused here. Could you elaborate please?

**Comment by jmchilton** [comment]
My understanding is we can branch with open 18.01 issues - just not with open 18.01 PRs. I was hoping to get to this after the branch and before the release since it is a bug fix.

Aside @mvdbeek has fixed it in https://github.com/galaxyproject/galaxy/pull/5413 I believe.

**Comment by martenson** [comment]
@jmchilton thanks for clarification, I agree issues are not release blocking - I meagerly wanted to ping you since this one sounded serious :)
