### PR TITLE
[25.1] Do not update a user's update_time when an admin archives (and purges) a history

### LINKED ISSUE #17809: Feature request: history archival without updating user `update_time`
We're using [gxyarchiver](https://github.com/galaxyproject/gxyarchiver) with `gxadmin query archivable-histories` to archive old histories. Currently this process causes an update to the user's `update_time`. I have a hacky script to record all update times of users whose histories will be archived in a batch, and then I reset their update time after the batch is done. Ideally, there'd be an (admin-only?) param in the API to prevent the update.

I am not sure which step actually causes the update (triggering the remote files export, or purging the history).

### PR DESCRIPTION
**Pull request by natefoo**
Fixes #17809.

Thanks to Claude I finally did TDD for the first time on this project. :stuck_out_tongue_winking_eye:

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: test/integration/test_history_archiving.py [hunk 1]
```diff
@@ -239,3 +243,110 @@ def _export_history_to_short_term_storage(self, history_id):
         self.dataset_populator.wait_for_export_task_on_record(last_record)
         assert last_record["ready"] is True
         return last_record
+
+
+class TestHistoryArchivingUserUpdateTime(PosixFileSourceSetup, IntegrationTestCase):
```
Comment (jmchilton) [inline test/integration/test_history_archiving.py]: Very nice. Ask Claude if it has any reason to not just add these test methods to the existing class in this directory? The Galaxy config looks the same so I wouldn't create another test instance just for these two tests - but maybe it has a good reason.

Comment (natefoo) [reply test/integration/test_history_archiving.py]: I'm sure its reason is "the idiot writing the prompts doesn't really have a lot of experience with our test structure" lol

Comment (natefoo) [reply test/integration/test_history_archiving.py]: Ah well we'd have to set the `require_admin_user` class property, not sure if we want to do that for the existing tests. Do we have a per-test-method way to do it?

Comment (jmchilton) [reply test/integration/test_history_archiving.py]: Actually that is a perfect reason IMO - I say ship it!

Comment (jmchilton) [reply test/integration/test_history_archiving.py]: https://gist.github.com/jmchilton/341f20f0683b05e68a75790ed90f8390

**Review by jmchilton — APPROVED** [review]
The changes I would make are outlined in https://gist.github.com/jmchilton/341f20f0683b05e68a75790ed90f8390 but it is also fine as it. Thanks for the tests Nate!

**Comment by natefoo** [comment]
I will of course take your changes, do you want to just push them?

I took a crack at the mypy errors but this one is particularly challenging since `sa_session.bind` can be so many things:

```
lib/galaxy/model/__init__.py:1130: error: Item "None" of
"Union[Engine, Connection, None]" has no attribute "connect"  [union-attr]
                    with engine.connect() as conn, conn.begin():
                         ^~~~~~~~~~~~~~
```

Even if you assert the attributes you want as we appear to do elsewhere, you just end up with additional errors:

```
lib/galaxy/model/__init__.py:1109: error: Item "Connection" of "Engine | Connection" has no attribute "connect"  [union-attr]
                    assert sa_session.bind.connect
                           ^~~~~~~~~~~~~~~~~~~~~~~
lib/galaxy/model/__init__.py:1133: error: Item "Connection" of "Engine | Connection" has no attribute "connect"  [union-attr]
                    with engine.connect() as conn, conn.begin():
                         ^~~~~~~~~~~~~~
```

What would be the preferred way to deal with this be?

**Comment by nsoranzo** [comment]
Not sure if this 100% equivalent in SQLAlchemy, but this fixes the mypy errors for me:

```diff
diff --git a/lib/galaxy/model/__init__.py b/lib/galaxy/model/__init__.py
index 369a261b48..66cde31bfc 100644
--- a/lib/galaxy/model/__init__.py
+++ b/lib/galaxy/model/__init__.py
@@ -1098,31 +1098,32 @@ WHERE user_id = :user_id and quota_source_label = :label
                 self.disk_usage = (self.disk_usage or 0) + amount
             else:
                 # else would work on newer sqlite - 3.24.0
-                engine = required_object_session(self).bind
-                if "sqlite" in engine.dialect.name:
+                session = required_object_session(self)
+                assert session.bind is not None
+                if "sqlite" in session.bind.dialect.name:
                     # hacky alternative for older sqlite
-                    statement = """
+                    statement_str = """
 WITH new (user_id, quota_source_label) AS ( VALUES(:user_id, :label) )
 INSERT OR REPLACE INTO user_quota_source_usage (id, user_id, quota_source_label, disk_usage)
 SELECT old.id, new.user_id, new.quota_source_label, COALESCE(old.disk_usage + :amount, :amount)
 FROM new LEFT JOIN user_quota_source_usage AS old ON new.user_id = old.user_id AND NEW.quota_source_label = old.quota_source_label;
 """
                 else:
-                    statement = """
+                    statement_str = """
 INSERT INTO user_quota_source_usage(user_id, disk_usage, quota_source_label)
 VALUES(:user_id, :amount, :label)
 ON CONFLICT
     ON constraint uqsu_unique_label_per_user
     DO UPDATE SET disk_usage = user_quota_source_usage.disk_usage + :amount
 """
-                statement = text(statement)
+                statement = text(statement_str)
                 params = {
                     "user_id": self.id,
                     "amount": int(amount),
                     "label": quota_source_label,
                 }
-                with engine.connect() as conn, conn.begin():
-                    conn.execute(statement, params)
+                with session.begin():
+                    session.execute(statement, params)
 
     def _get_social_auth(self, provider_backend):
         if not self.social_auth:
```

**Comment by jdavcs** [comment]
> Not sure if this 100% equivalent in SQLAlchemy, but this fixes the mypy errors for me:

Yes, it is equivalent.

**Comment by nsoranzo** [comment]
I've pushed another commit to fix the unit tests, feel free to drop it if there's a better solution.

File: lib/galaxy/webapps/galaxy/services/histories.py [hunk 2]
```diff
@@ -731,7 +731,9 @@ def archive_history(
                 raise glx_exceptions.RequestParameterMissingException(
                     "Cannot purge history without an export record. A valid archive_export_id is required."
                 )
-            self.manager.purge(history)
+            # Preserve owner's update_time when admin archives another user's history
+            preserve_owner_update_time = trans.user and history.user_id and trans.user.id != history.user_id
```
Comment (nsoranzo) [inline lib/galaxy/webapps/galaxy/services/histories.py]:
```suggestion
            preserve_owner_update_time = trans.user and history.user_id is not None and trans.user.id != history.user_id
```

**Comment by natefoo** [comment]
Thank you all!

**Comment by mvdbeek** [comment]
If I'm not mistaken this is the first PR that led to No space left on disk: https://github.com/galaxyproject/galaxy/actions/runs/20469545248/job/58821408376#step:13:6497
