### ISSUE TITLE
The "Join MAF blocks" (`MAF_Thread_For_Species1`) uses a function in bx-python that does not appear to exist

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#16968]
**Describe the bug**
Running the tool test on usegalaxy.org, I get this error:
```pytb
Traceback (most recent call last):
  File "/jetstream2/scratch/main/jobs/53417378/tool_files/maf_thread_for_species.py", line 17, in <module>
    from bx.align.tools.thread import (
ImportError: cannot import name 'remove_all_gap_columns' from 'bx.align.tools.thread' (/cvmfs/main.galaxyproject.org/venv/lib/python3.8/site-packages/bx/align/tools/thread.py)
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.2.dev0
Commit: a2e3972ed290834e956f869a8afc48bbdfaa3031

**To Reproduce**
```
galaxy-tool-test -u https://usegalaxy.org/ -t MAF_Thread_For_Species1
```

**Expected behavior**
The tool works

**Screenshots**
N/A

**Additional context**
https://usegalaxy.org/datasets/f9cad7b01a4721351e757c773adc3d15/details

**Comment by nsoranzo** [comment]
Ah, this is not requiring a bx-python version but using it from Galaxy virtual env, so it broke with https://github.com/bxlab/bx-python/pull/77 .
I think this is easily fixable in the Python script, right @lldelisle ?

**Comment by lldelisle** [comment]
If I remember correctly this piece of code was present twice as (as an independent function in thread and as a method of Alignment objects). That's why I removed it. The PR #16971 should fix it.

**Comment by bernt-matthias** [comment]
I would be in favor of moving all those tools to somewhere where they are tested and run containerized.

**Comment by lldelisle** [comment]
I also think that these tools should go to iuc...
