### PR TITLE
[20.01] Fix wiggle estimated_display_viewport

### PR DESCRIPTION
**Pull request by mvdbeek**
Broken in https://github.com/galaxyproject/galaxy/pull/9415, where I
used the wrong function name.
Fixes https://sentry.galaxyproject.org/sentry/main/issues/568813/:
```
AttributeError: module 'galaxy.util' has no attribute 'iter_readline_count'
  File "galaxy/datatypes/interval.py", line 1092, in get_estimated_display_viewport
    for line in util.iter_readline_count(fh, VIEWPORT_READLINE_BUFFER_SIZE):
```

### CODE REVIEW

**Comment by dannon** [comment]
I'll backport that pytest fix to 20.01 so those work again.  This looks good though.
