### PR TITLE
[18.09] Fix process key

### LINKED ISSUE #7048: Uncaught exception in lib/galaxy/tools/parameters/meta.py
Hey,
After updating to 18.09, when running biomaj2galaxy to run some data managers, I get this exception:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 418, in create
    return self._create(trans, payload, **kwd)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 476, in _create
    vars = tool.handle_input(trans, incoming, history=target_history, use_cached_job=use_cached_job)
  File "lib/galaxy/tools/__init__.py", line 1385, in handle_input
    all_params, all_errors, rerun_remap_job_id, collection_info = self.expand_incoming(trans=trans, incoming=incoming, request_context=request_context)
  File "lib/galaxy/tools/__init__.py", line 1340, in expand_incoming
    expanded_incomings, collection_info = expand_meta_parameters(trans, self, incoming)
  File "lib/galaxy/tools/parameters/meta.py", line 118, in expand_meta_parameters
    process_key(incoming_key, d=nested_dict)
  File "lib/galaxy/tools/parameters/meta.py", line 87, in process_key
    d[input_name].append(subdict)
AttributeError: 'object' object has no attribute 'append'
```
It looks like this code comes from https://github.com/galaxyproject/galaxy/commit/bf206c870b793edda71aaa5655baeca070e3729a, but I'm not sure how to fix it

### PR DESCRIPTION
**Pull request by mvdbeek**
This should fix #7048

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

File: lib/galaxy/tools/parameters/meta.py [hunk 1]
```diff
@@ -72,26 +72,30 @@ def expand_workflow_inputs(inputs):
...
         if input_name not in d:
             d[input_name] = []
-        subdict = {}
-        d[input_name].append(subdict)
-        process_key("|".join(key_parts[1:]), d=subdict)
+        if len(d[input_name]) > index:
+            subdict = d[input_name][index]
+        else:
+            subdict = {}
+            d[input_name].append(subdict)
```
Comment (nsoranzo) [inline lib/galaxy/tools/parameters/meta.py:91]: @mvdbeek I'm not completely convinced this code is correct: if the repeat elements are not sorted in the `incoming` dictionary, the element with `index` N can be appended here in a position < N.
