### ISSUE TITLE
Azure SSO fails on 25.1.0: AttributeError: 'AzureADV2TenantOAuth2' object has no attribute 'find_valid_key' during callback

### ISSUE THREAD

**Issue by JasperBoomBejo** [galaxyproject/galaxy#21502]
Hello Galaxy team!

I hope someone could help me with this problem 😄.

After upgrading our internal Galaxy instance from v25.0.3 to v25.1.0, Azure SSO logins consistently fail at the callback step with:

```bash
  81214 galaxy.authnz.managers ERROR 2025-12-22 15:24:22,442 [pN:main.3,p:518,tN:WSGI_0] An error occurred when handling callback from `azure` identity provider.  Please contact an admini>
  81215 Traceback (most recent call last):
  81216   File "/galaxy/lib/galaxy/authnz/managers.py", line 361, in callback
  81217     return success, message, backend.callback(state_token, authz_code, trans, login_redirect_url)
  81218   File "/galaxy/lib/galaxy/authnz/psa_authnz.py", line 254, in callback
  81219     redirect_url = do_complete(
  81220   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/actions.py", line 65, in do_complete
  81221     user = backend.complete(*args, user=user, redirect_name=redirect_name, **kwargs)
  81222   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/base.py", line 61, in complete
  81223     return self.auth_complete(*args, **kwargs)
  81224   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/utils.py", line 250, in wrapper
  81225     return func(*args, **kwargs)
  81226   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/oauth.py", line 486, in auth_complete
  81227     return self.do_auth(
  81228   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/utils.py", line 250, in wrapper
  81229     return func(*args, **kwargs)
  81230   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/oauth.py", line 499, in do_auth
  81231     return self.strategy.authenticate(*args, **kwargs)
  81232   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/strategy.py", line 202, in authenticate
  81233     return backend.authenticate(*args, **kwargs)
  81234   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/base.py", line 106, in authenticate
  81235     return self.pipeline(pipeline, *args, **kwargs)
  81236   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/base.py", line 111, in pipeline
  81237     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  81238   File "/galaxy/.venv/lib/python3.10/site-packages/social_core/backends/base.py", line 145, in run_pipeline
  81239     result = func(*args, **out) or {}
  81240   File "/galaxy/lib/galaxy/authnz/psa_authnz.py", line 544, in decode_access_token
  81241     access_token_data = _decode_access_token_helper(token_str=access_token_encoded, backend=backend)
  81242   File "/galaxy/lib/galaxy/authnz/psa_authnz.py", line 567, in _decode_access_token_helper
  81243     signing_key = backend.find_valid_key(token_str)
  81244 AttributeError: 'AzureADV2TenantOAuth2' object has no attribute 'find_valid_key'
```

Environment
- Galaxy version: 25.1.0 (Docker)
- Previous working version: 25.0.3 (same configs)
- Auth provider: Microsoft Azure AD (OIDC, v2 tenant)
- social-auth-core: tested with 3.7.0 and 3.8.3 (upgrading did not help)
- Deployment: Docker container (internal instance)

What changed:
We rebuilt our image to 25.1.0 and re-applied our existing OIDC adjustments to the new config files. No intentional change to auth settings other than keeping them in sync with the new release.

Expected behavior:
Azure SSO should complete successfully and (for first‑time users) automatically create a Galaxy user account.

Actual behavior:
Callback fails with AttributeError as shown above, and users see the generic “Please contact an administrator” error banner.

Config snippet (sanitized)
oidc_backends_config.xml (key parts; secrets removed):
```xml
<?xml version="1.0"?>
<OIDC>
  <provider name="azure">
    <client_id>someid</client_id>
    <client_secret>someid</client_secret>
    <redirect_uri>https://someurl/authnz/azure/callback</redirect_uri>
    <tenant_id>someid</tenant_id>
    <custom_button_text>sometext</custom_button_text>
  </provider>
</OIDC>
```

We also tried adding: `<extra_scopes>openid,profile,email</extra_scopes>`.

Does anyone have an idea? Thank you for the help!

**Comment by bgruening** [comment]
Which version of python-social-auth is installed? Can you maybe try to downgrade the version?

**Comment by JasperBoomBejo** [comment]
> Which version of python-social-auth is installed? Can you maybe try to downgrade the version?

I tested with both versions 3.7.0 and 3.8.3. Which version do you suggest I test?

**Comment by JasperBoomBejo** [comment]
The issue seems to be that Galaxy added the `decode_access_token` step to the default OIDC pipeline. Earlier versions didn’t run this extra verification step, so the Azure backend was never asked for `find_valid_key()` and it was handled interanlly, which is why we were able to use OIDC for our setup.

The docstring in `lib/galaxy/authnz/oidc_utils.py` mentions:
```
OIDC-specific utility functions for token handling and verification.

This module contains helper functions that are specific to OpenID Connect (OIDC)
authentication. These should not be used with non-OIDC backends like OAuth2.
```

However, the Azure v2 tenant backend in social-core is OIDC but uses its own verification approach and doesn’t expose a find_valid_key() helper.

I guess the Galaxy backend for OIDC authentication should be made Azure PSA aware, and skip this decode step or make use of the Azure backend’s JWKS/certificate logic somehow?

**Comment by JasperBoomBejo** [comment]
I currently have a work around:
```yaml
  oidc_auth_pipeline:
  - "social_core.pipeline.social_auth.social_details"
  - "social_core.pipeline.social_auth.social_uid"
  - "social_core.pipeline.social_auth.auth_allowed"
  - "galaxy.authnz.psa_authnz.contains_required_data"
  - "galaxy.authnz.psa_authnz.verify"
  - "social_core.pipeline.social_auth.social_user"
  - "social_core.pipeline.user.get_username"
  - "social_core.pipeline.social_auth.associate_by_email"
  - "social_core.pipeline.user.create_user"
  - "social_core.pipeline.social_auth.associate_user"
  - "social_core.pipeline.social_auth.load_extra_data"
  - "social_core.pipeline.user.user_details"
```

Which disables the decoding step, but is not ideal.
