### PR TITLE
[19.05] Fix importing a directory from user_library_import_dir

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix the following traceback:

```
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy/lib/galaxy/webapps/galaxy/api/library_contents.py", line 250, in create
    status, output = self._upload_library_dataset(trans, library_id, real_folder_id, **payload)
  File "/galaxy/lib/galaxy/webapps/galaxy/api/library_contents.py", line 337, in _upload_library_dataset
    **kwd)
  File "/galaxy/lib/galaxy/actions/library.py", line 91, in _upload_dataset
    full_dir, import_dir_desc = validate_server_directory_upload(trans, server_dir)
  File "/galaxy/lib/galaxy/actions/library.py", line 48, in validate_server_directory_upload
    if import_dir_desc == 'user_library_import_dir' and safe_contains(import_dir, full_dir, whitelist=trans.app.config.user_library_import_symlink_whitelist, username=username):
TypeError: safe_contains() got an unexpected keyword argument 'username'
```

Also add a test case to reproduce the fixed issue, which was introduced in commit f4442ffc807285a96fa049f9a7e961b5e945bbff .

Reported by @jhl667 .

### CODE REVIEW

**Comment by crutching** [comment]
This fix worked for me, thanks!

**Comment by martenson** [comment]
~~Under what conditions is this happening?~~

edit: found the testcase, nevermind and thanks!

**Comment by nsoranzo** [comment]
The added test case should be equivalent to:
`POST /api/libraries/{library_id}/contents` specifying `create_type=file`, `upload_option=upload_directory` and a value for `server_dir` in the payload.

**Review by mvdbeek — APPROVED** [review]

**Comment by martenson** [comment]
I'm surprised we did not have test coverage for this :/
