### PR TITLE
Fix multiple flag for workflow dataset inputs

### LINKED ISSUE #1946: Workflow runs that use collection lists are broken
**Reported against commit 29b6d54.**

**When running a workflow that uses collection lists as parameters, the workflow fails to run with the server reporting:**

```
galaxy.workflow.run ERROR 2016-03-17 15:56:38,210 Failed to schedule Workflow[id=6,name= pipeline (imported from uploaded file)], problem occurred on WorkflowStep[index=0,type=data_input].                                                                                                                             
Traceback (most recent call last):                                                                                                                            
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke                                                            
    jobs = self._invoke_step( step )                                                                                                                          
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step                                                      
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )                                                                   
  File "/c8000xd3/galaxy/lib/galaxy/workflow/modules.py", line 487, in execute                                                       
    content_type = input_dataset_hda.history_content_type                                                                                                     
AttributeError: 'list' object has no attribute 'history_content_type'                                                                                         
galaxy.workflow.run ERROR 2016-03-17 15:56:38,324 Failed to execute scheduled workflow.                                                                       
Traceback (most recent call last):                                                                                                                            
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke                                                           
    outputs = invoker.invoke()                                                                                                                                
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke                                                            
    jobs = self._invoke_step( step )                                                                                                                          
  File "/c8000xd3/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step                                                      
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )                                                                   
  File "/c8000xd3/galaxy/lib/galaxy/workflow/modules.py", line 487, in execute                                                       
    content_type = input_dataset_hda.history_content_type                                                                                                     
AttributeError: 'list' object has no attribute 'history_content_type' 
```

**I've git-bisected this to be caused by the following commit:**

```
40c9e1af255b548c35a9d98ac4c196058d185541 is the first bad commit                                                                                              
commit 40c9e1af255b548c35a9d98ac4c196058d185541                                                                                                               
Author: guerler <aysam.guerler@gmail.com>                                                                                                                     
Date:   Wed Mar 9 10:33:42 2016 -0500                                                                                                                         

    Use value_to_basic and to_json when populating the tool model 
```

**Bisect log:**

```

git bisect start                                                                                                                                              
# good: [d6e38c7d482eae65fc135cd65a13b7f215220cd5] remove unused import                                                                                       
git bisect good d6e38c7d482eae65fc135cd65a13b7f215220cd5                                                                                                      
# bad: [29b6d545cf229518840e29d7468d65e4221db95a] Merge pull request #1926 from blankenberg/iobio-display                                                     
git bisect bad 29b6d545cf229518840e29d7468d65e4221db95a                                                                                                       
# good: [1e46198becdba27f98f7ce93bb27f21ae59392a1] Merge pull request #1602 from carlfeberhard/history.contents                                               
git bisect good 1e46198becdba27f98f7ce93bb27f21ae59392a1                                                                                                      
# good: [78b1f9af3741889a542d881cf242a12acc932a7e] Dockerfile testing improvements.                                                                           
git bisect good 78b1f9af3741889a542d881cf242a12acc932a7e                                                                                                      
# skip: [4cf90643580c4cda20b2076e9ebe2bb5660a4c75] Merge, rebuild client.                                                                                     
git bisect skip 4cf90643580c4cda20b2076e9ebe2bb5660a4c75                                                                                                      
# skip: [370ea10f75196e899868a248b1f301d4994debd8] Use real routes for tours, and make them actually work.  Now it's possible to open the tour index in a new tab, etc., instead of just using javascript craziness.                                                                                                        
git bisect skip 370ea10f75196e899868a248b1f301d4994debd8                                                                                                      
# skip: [8d71c3dc1b7ed1ad33f60af1f1fe71e4c7ece108] Change to sentry middleware to work with modern raven clients.  This allows us to upgrade raven and actually show the entire event_id to users on the guru meditation page.                                                                                              
git bisect skip 8d71c3dc1b7ed1ad33f60af1f1fe71e4c7ece108                                                                                                      
# good: [158732edb6ceb1ed073d058b3a71c4c26e4887d2] Merge pull request #1835 from jmchilton/from_editor_fix                                                    
git bisect good 158732edb6ceb1ed073d058b3a71c4c26e4887d2                                                                                                      
# skip: [773095d403929ad7f44561ff17f960f088f1b9ce] Unify json representation for regular datasets and collections                                             
git bisect skip 773095d403929ad7f44561ff17f960f088f1b9ce                                                                                                      
# good: [7955a2b769d02e57ed609b636621cd76d27bc3a8] Update run.mako                                                                                            
git bisect good 7955a2b769d02e57ed609b636621cd76d27bc3a8                                                                                                      
# good: [1aaf65e8b6306e3d4a7e69d545d9fe300c1510ca] missing ;; in case stop                                                                                    
git bisect good 1aaf65e8b6306e3d4a7e69d545d9fe300c1510ca                                                                                                      
# bad: [915993bbd8f82afef9b68f5d8820437a07f6f264] Add display_applications/iobio/vcf.xml.                                                                     
git bisect bad 915993bbd8f82afef9b68f5d8820437a07f6f264                                                                                                       
# bad: [79a0972675a3594292c7e28e36639d67d49863ad] Improve empty dataset check, handle from_json inconsistency                                                 
git bisect bad 79a0972675a3594292c7e28e36639d67d49863ad                                                                                                       
# bad: [b1a9823a3c596a303973b8e1dbbd734a67c392ef] Remove RuntimeValue arrays                                                                                  
git bisect bad b1a9823a3c596a303973b8e1dbbd734a67c392ef                                                                                                       
# bad: [40c9e1af255b548c35a9d98ac4c196058d185541] Use value_to_basic and to_json when populating the tool model                                               
git bisect bad 40c9e1af255b548c35a9d98ac4c196058d185541                                                                                                       
# good: [14d6e34e010cafd98d8db2680c4c339e727c968d] Rename from_html to from_json                                                                              
git bisect good 14d6e34e010cafd98d8db2680c4c339e727c968d                              


```

### PR DESCRIPTION
**Pull request by guerler**
Fixes #1946. ping @einon

### CODE REVIEW

**Comment by jmchilton** [comment]
It was set this way to render the batch selection dialog in the workflow run form. The batching done there is different than the tool form - it doesn't handle collections, etc... If it works without this hack on the frontend for whatever reason - I'm fine with fixing this.

**Comment by guerler** [comment]
Thanks a lot for looking into it @jmchilton. It looks as if the multiple flag is removed manually, regardless of the module parameter definition: https://github.com/galaxyproject/galaxy/commit/a8285d61609116622befb099ed27bcad21139c9a#diff-045bd6f46077946f5e9adcf4d407d367R59. So the field is displayed as single select even if configured as multi-select.

**Comment by ghost** [comment]
This now works fine for my test case - thank you for fixing!

There's a good explanation of why the bug occurs in the conversation above, so why didn't that go into the git commit message? Past experience makes me pretty sure that a few months down the line, even those working on the fix won't remember what it's about.

I'm all for the points raised in, for example, http://chris.beams.io/posts/git-commit/ being considered. The majority of git committers for this project could do with being aware of these, IMHO. It would make git archaeology easier for outsiders like me.

**Comment by gregvonkuster** [comment]
I heartily agree with comments from @einon above!
