### ISSUE TITLE
New-ish exceptions in sentry after updating to 21.01 

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11286]
- [x] https://sentry.galaxyproject.org/sentry/main/issues/1214736/ (this one probably appeared somewhere on 20.09):
```
AttributeError: 'MutationList' object has no attribute '_key'
  File "galaxy/tools/__init__.py", line 1660, in handle_single_execution
    flush_job=flush_job,
  File "galaxy/tools/__init__.py", line 1748, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "galaxy/tools/actions/model_operations.py", line 65, in execute
    job_callback(job)
  File "galaxy/workflow/modules.py", line 1756, in <lambda>
    job_callback=lambda job: self._handle_post_job_actions(step, job, invocation.replacement_dict),
  File "galaxy/workflow/modules.py", line 1809, in _handle_post_job_actions
    ActionBox.execute(self.trans.app, self.trans.sa_session, pja, job, replacement_dict)
  File "galaxy/jobs/actions/post.py", line 517, in execute
    ActionBox.actions[pja.action_type].execute(app, sa_session, pja, job, replacement_dict)
  File "galaxy/jobs/actions/post.py", line 103, in execute
    app.datatypes_registry.change_datatype(dataset_instance, action.action_arguments['newtype'])
  File "galaxy/datatypes/registry.py", line 590, in change_datatype
    data.init_meta(copy_from=data)
  File "galaxy/model/__init__.py", line 2897, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "galaxy/datatypes/interval.py", line 79, in init_meta
    Tabular.init_meta(self, dataset, copy_from=copy_from)
  File "galaxy/datatypes/data.py", line 182, in init_meta
    dataset.metadata = copy_from.metadata
  File "galaxy/model/__init__.py", line 2808, in set_metadata
    self._metadata = self.metadata.make_dict_copy(bunch)
  File "galaxy/model/metadata.py", line 163, in make_dict_copy
    rval[key] = self.spec[key].param.make_copy(value, target_context=self, source_context=to_copy)
  File "galaxy/model/metadata.py", line 283, in make_copy
    return copy.deepcopy(value)
  File "python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "galaxy/model/custom_types.py", line 232, in __deepcopy__
    return MutationList(MutationObj.coerce(self._key, copy.deepcopy(self[:])))
```
- [x] https://sentry.galaxyproject.org/sentry/main/issues/1313989/:
```
TypeError: 'NoneType' object is not callable
  File "galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/datasets.py", line 176, in show_storage
    name = object_store.get_concrete_store_name(dataset)
  File "galaxy/objectstore/__init__.py", line 316, in get_concrete_store_name
    return self._invoke('get_concrete_store_name', obj)
  File "galaxy/objectstore/__init__.py", line 286, in _invoke
    return self.__getattribute__("_" + delegate)(obj=obj, **kwargs)
  File "galaxy/objectstore/__init__.py", line 704, in _get_concrete_store_name
    return self._call_method('_get_concrete_store_name', obj, None, True)
  File "galaxy/objectstore/__init__.py", line 898, in _call_method
    % (method, self._repr_object_for_exception(obj), str(kwargs)))
```
- [ ] https://sentry.galaxyproject.org/sentry/main/issues/1315243/ -- could be pulsar maybe ? `target_dir` is `''`
```
FileNotFoundError: [Errno 2] No such file or directory: ''
  File "galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/job_files.py", line 104, in create
    util.safe_makedirs(target_dir)
  File "galaxy/util/path/__init__.py", line 112, in safe_makedirs
    makedirs(path)
  File "python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
```
- [x] https://sentry.galaxyproject.org/sentry/main/issues/1325262/ -- https://github.com/galaxyproject/galaxy/pull/11355
```
AttributeError: module 'itertools' has no attribute 'izip'
  File "galaxy/util/__init__.py", line 1039, in unicodify
    value = str(value)
  File "Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1613100127_944503_14259.py", line 601, in respond
  File "cheetah_DynamicallyCompiledCheetahTemplate_1613100127_944503_14259.py", line 154, in read_group_name_default
```
This used to work using 2to3

This is not actually an error, this is just confusing new logging.

- [x] https://sentry.galaxyproject.org/sentry/main/issues/1313988/ -- https://github.com/galaxyproject/galaxy/pull/11354
```
TypeError: 'NoneType' object is not iterable
  File "galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/jobs.py", line 329, in destination_params
    return summarize_destination_params(trans, job)
  File "galaxy/managers/jobs.py", line 613, in summarize_destination_params
    destination_params.update(job.destination_params)
```
- [x] https://sentry.galaxyproject.org/sentry/main/issues/1325196/ -- https://github.com/galaxyproject/galaxy/pull/11353
```
AttributeError: null
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/middleware/statsd.py", line 33, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 136, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 215, in handle_request
    body = method(trans, **kwargs)
  File "galaxy/webapps/galaxy/controllers/visualization.py", line 488, in display_by_username_and_slug
    visualization_config = self.get_visualization_config(trans, visualization)
  File "galaxy/webapps/base/controller.py", line 1035, in get_visualization_config
    tracks.append(pack_track(drawable_dict))
  File "galaxy/webapps/base/controller.py", line 996, in pack_track
    "filters": track_dict.get('filters', {'filters' : track_data_provider.get_filters()}),
  File "galaxy/visualization/data_providers/genome.py", line 249, in get_filters
    if self.original_dataset.metadata.viz_filter_cols:
  File "galaxy/model/metadata.py", line 116, in __getattr__
    raise AttributeError
```

**Comment by mvdbeek** [comment]
[ ] https://sentry.galaxyproject.org/sentry/main/issues/1325262/
```
AttributeError: module 'itertools' has no attribute 'izip'
  File "galaxy/util/__init__.py", line 1039, in unicodify
    value = str(value)
  File "Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1613100127_944503_14259.py", line 601, in respond
  File "cheetah_DynamicallyCompiledCheetahTemplate_1613100127_944503_14259.py", line 154, in read_group_name_default
```
This used to work using 2to3

**Comment by mvdbeek** [comment]
- [ ] https://sentry.galaxyproject.org/sentry/main/issues/1313988/
```
TypeError: 'NoneType' object is not iterable
  File "galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/jobs.py", line 329, in destination_params
    return summarize_destination_params(trans, job)
  File "galaxy/managers/jobs.py", line 613, in summarize_destination_params
    destination_params.update(job.destination_params)
```
- [ ] https://sentry.galaxyproject.org/sentry/main/issues/1325196/
```
AttributeError: null
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/middleware/statsd.py", line 33, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 136, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 215, in handle_request
    body = method(trans, **kwargs)
  File "galaxy/webapps/galaxy/controllers/visualization.py", line 488, in display_by_username_and_slug
    visualization_config = self.get_visualization_config(trans, visualization)
  File "galaxy/webapps/base/controller.py", line 1035, in get_visualization_config
    tracks.append(pack_track(drawable_dict))
  File "galaxy/webapps/base/controller.py", line 996, in pack_track
    "filters": track_dict.get('filters', {'filters' : track_data_provider.get_filters()}),
  File "galaxy/visualization/data_providers/genome.py", line 249, in get_filters
    if self.original_dataset.metadata.viz_filter_cols:
  File "galaxy/model/metadata.py", line 116, in __getattr__
    raise AttributeError
```
