### ISSUE TITLE
Error with BIOM upload and generation on 19.01

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#7625]
Hi, 

The upload and generation of BIOM file are raising errors on 19.01, not on 18.09.

**Issue**: 
```
ERROR:galaxy.datatypes.text:Something in the metadata detection for biom1 went wrong.
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/datatypes/text.py", line 259, in set_meta
    for k, v in column['metadata'].items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Usecase**: 
- Upload biom file on usegalaxy.eu but also using Planemo (no error but same info in stdout)
- MetaPhan2 on usegalaxy, but also using Planemo (error)

**How to reproduce it**:
- usegalaxy.eu (19.01)
	- Upload biom file: no error but same info in stdout
    - Run MetaPhan2: tool failing with the message
- 19.01 using planemo
    - Run MetaPhan2: tool failing with the message
- 18.09 using planemo
    - Run MetaPhan2: tool not failing

The piece of code pointed by the error has been modified in [6dd098f747c89ba](https://github.com/galaxyproject/galaxy/commit/6dd098f747c89ba3494b64bb5a64dc078bb3d5db#diff-29996c0d5f723a702ea671841bacefa3) on Nov 7, 2018. 
@nsoranzo do you think your changes may cause the error or it is a previous change (looks like there were several changes on the same portion in the days before)?
Do you have any idea how we can fix that?
I will investigate later otherwise

Thanks a lot

Bérénice

**Comment by nsoranzo** [comment]
It seems `column['metadata']` is `None`, so also before my commit `Biom1.set_meta()` would have failed at:
```python
                                for k in column['metadata']:
```

**Comment by nsoranzo** [comment]
I think it was introduced in commit 258ada862ece5a06b8a86530cd9f22c355a80ac1 , but anyway part of PR https://github.com/galaxyproject/galaxy/pull/6972 .

**Comment by bebatut** [comment]
thank for the quick answer and the links 😄 
I definitely need investigate more later
