### ISSUE TITLE
Empty select-input treated as [] instead of "None" in 20.05

### ISSUE THREAD

**Issue by AndreasSko** [galaxyproject/galaxy#9773]
I'm trying to run [this](https://github.com/usegalaxy-eu/workflow-testing/blob/master/sklearn/ard/ard.ga) workflow on 20.05 (using Planemo test), which worked in 20.01 with Python 3. When running the sklearn_searchcv-tool the error occurs:

> Traceback (most recent call last):
>   File "/galaxy/database/jobs_directory/000/4/configs/tmp_1z1p9jo", line 72, in <module>
>     options['scoring'] = get_scoring(options['scoring'])
>   File "<string>", line 295, in get_scoring
> AttributeError: 'list' object has no attribute 'split'
> ]

In the end I tracked the error down to Galaxy "interpreting" an empty `select`-input differently between 20.01 and 20.05:

**20.01:**
```
"options": {
      "scoring": {
        "secondary_scoring": "None",
        "primary_scoring": "r2"
      },
```
**20.05:**
```
"scoring": {
        "secondary_scoring": [],
        "primary_scoring": "r2"
      },
```

However, I'm not sure if this change is actually desired or considered a bug..

The full inputs for the tool:
[20.01_py3.txt](https://github.com/galaxyproject/galaxy/files/4635700/20.01_py3.txt)
[20.05_py3.txt](https://github.com/galaxyproject/galaxy/files/4635701/20.05_py3.txt)

**Comment by AndreasSko** [comment]
(seems to have been introduced by https://github.com/galaxyproject/galaxy/commit/f25192b533a7b00069284e1350099637d44cf412)

**Comment by bernt-matthias** [comment]
Jep. This was changed here: https://github.com/galaxyproject/galaxy/pull/9279 and I still think that the change is desired which unfortunately breaks this tool. 

Question is how to deal with this. Do we need a profile for this?

**Comment by mvdbeek** [comment]
I agree that the new format is more correct and allows you to write better code that consumes the json.
I think a new profile probably makes sense if you can restore the old behavior conditionally.

**Comment by bernt-matthias** [comment]
Do you have a link to code where I could see how this is done. Then I could take care of this.

**Comment by bernt-matthias** [comment]
I guess I worked it out myself: https://github.com/galaxyproject/galaxy/pull/9776

**Comment by mvdbeek** [comment]
You mean the profile ? It's an attribute of the Tool class. In the `json_wrap` case you could pass the profile version here: https://github.com/galaxyproject/galaxy/blob/b8da698b239a11d93a3f78d382666fda3ec58c51/lib/galaxy/tools/evaluation.py#L610

**Comment by mvdbeek** [comment]
I see you already figured this out.
