### PR TITLE
Fix is_of_type for datasets in a collection

### PR DESCRIPTION
**Pull request by mvdbeek**
Include a test tool that fails like this without the fix:

```
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/template.py", line 80, in fill_template
    return unicodify(t, log_exception=False)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/__init__.py", line 1060, in unicodify
    value = str(value)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1631180564_759418_48584.py", line 89, in respond
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 342, in is_of_type
    datatype = self.datatypes_registry.get_datatype_by_extension(e)
AttributeError: 'NoneType' object has no attribute 'get_datatype_by_extension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/runners/__init__.py", line 237, in prepare_job
    job_wrapper.prepare()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/__init__.py", line 1160, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/evaluation.py", line 463, in build
    raise e
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/evaluation.py", line 459, in build
    self.__build_command_line()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/evaluation.py", line 484, in __build_command_line
    command_line = fill_template(command, context=param_dict, python_template_version=self.tool.python_template_version)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/template.py", line 118, in fill_template
    return fill_template(template_text=template_text,
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/template.py", line 126, in fill_template
    raise first_exception or e
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/template.py", line 80, in fill_template
    return unicodify(t, log_exception=False)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/__init__.py", line 1060, in unicodify
    value = str(value)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1631180564_725492_78593.py", line 87, in respond
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 342, in is_of_type
    datatype = self.datatypes_registry.get_datatype_by_extension(e)
AttributeError: 'NoneType' object has no attribute 'get_datatype_by_extension'
```

Broken in https://github.com/galaxyproject/galaxy/pull/11613

Reported by @natefoo on gitter.

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by natefoo — APPROVED** [review]
Thanks @mvdbeek !

**Comment by dannon** [comment]
Failing test is hopefully fixed now with #12423, but is unrelated anyway.
