### ISSUE TITLE
[17.01] Base JobState class does not have .cleanup() method

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3801]
This breaks when using the local runner:

```
galaxy.jobs.runners ERROR 2017-03-22 11:53:04,424 (1778) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "galaxy/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "galaxy/lib/galaxy/jobs/runners/local.py", line 133, in queue_job
    self._fail_job_local(job_wrapper, "Unable to finish job")
  File "galaxy/lib/galaxy/jobs/runners/local.py", line 173, in _fail_job_local
    self.fail_job(job_state, exception=True)
  File "galaxy/lib/galaxy/jobs/runners/__init__.py", line 381, in fail_job
    job_state.cleanup()
AttributeError: 'JobState' object has no attribute 'cleanup'
```

**Comment by jmchilton** [comment]
Broken by that moron @jmchilton in https://github.com/galaxyproject/galaxy/pull/3291/commits/b78287f1508db2c06f0c309ed8d3747adb4d17fa as part of #3291.
