### PR TITLE
[16.01] Fix #1538.

### LINKED ISSUE #1538: Loading a workflow into the editor fails to completely load, without user notice
User did have a history that contained a collection of list:paired, along with additional datasets. Workflow is listed as having 33 steps, but loading into the editor only displays a single input collections box (no errors are relayed to the user). This error is thrown in the logs:

```
galaxy.tools ERROR 2016-01-19 15:16:40,771 tools::to_json() - Skipping parameter expansion for input_collection.
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 2322, in iterate
    tool_dict = input.to_dict(trans, other_values=other_values)
  File "lib/galaxy/tools/parameters/basic.py", line 2449, in to_dict
    subcollection_type = self._history_query( trans ).collection_type_description.collection_type
AttributeError: 'HistoryQuery' object has no attribute 'collection_type_description'
```

When user has an empty history, the workflow still only loads up one workflow module, but no error is logged.

Copying the user's workflow, shows the copy to still have 33 steps (on workflow list), but loading the copy exhibits the same behavior as above (error logged with non-empty history, no error logged with empty history, no message to user, single box in the workflow editor shown to the user).

Experienced on Test: {"version_major": "16.04"}. Not tested elsewhere.

### PR DESCRIPTION
**Pull request by jmchilton**
Displaying subcollection mapping in tool forms was broken with #1308 - this fixes that I believe.

### CODE REVIEW

**Comment by blankenberg** [comment]
+1 (error looks to be PIP related)
