### PR TITLE
[19.09] Fix 'NoneType' object has no attribute 'get_tool_relative_path' with data_manager_manual

### PR DESCRIPTION
**Pull request by abretaud**
While running biomaj2galaxy tests with Galaxy 19.05 I get this error when trying to populate a data table with the [manual data manager](https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_manual):

```
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 224, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 863, in prepare
    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
  File "lib/galaxy/tools/evaluation.py", line 118, in set_compute_environment
    out_data=out_data, tool=self.tool, param_dict=incoming)
  File "lib/galaxy/tools/__init__.py", line 1719, in call_hook
    return code(*args, **kwargs)
  File "../shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_manual/6524e573d9c2/data_manager_manual/data_manager/data_manager_manual.py", line 57, in exec_before_job
    target_dir, tool_path, relative_target_dir = tdtm.get_target_install_dir( tool_shed_repository )
  File "lib/tool_shed/tools/data_table_manager.py", line 111, in get_target_install_dir
    tool_path, relative_target_dir = tool_shed_repository.get_tool_relative_path(self.app)
AttributeError: Error in 'Manual Data Manager' hook 'exec_before_job', original message: 'NoneType' object has no attribute 'get_tool_relative_path'
```

I guess the bug was introduced in #7316, a tool_shed_repository object was no longer accessible from the data manager code.

I tested the patch with 19.05, but it should work the same with 19.09 (too late to test this week :) )

It would be cool to have it backported to 19.05 too (I have a branch ready for that if needed https://github.com/galaxyproject/galaxy/compare/release_19.05...abretaud:dmfix1905?expand=1)

(There's another PR in IUC to fix another problem in the data manager https://github.com/galaxyproject/tools-iuc/pull/2634)

### CODE REVIEW

**Review by mvdbeek — DISMISSED** [review]
This looks like a good fix, though I noticed that data managers in repos without install database will fail since they don't have `get_tool_relative_path`. We should be able to fix that too, I'll take a look.

**Comment by abretaud** [comment]
Thanks for merging! Is it possible to have it backported to 19.05? It would repair biomaj2galaxy for people running 19.05 (including me ;))

**Comment by mvdbeek** [comment]
I'm working on it, I don't think this works as is.

**Comment by abretaud** [comment]
Arf, ok thanks!

**Comment by martenson** [comment]
superseded by https://github.com/galaxyproject/galaxy/pull/8817

thanks @abretaud !
