### PR TITLE
fix condor containers

### LINKED ISSUE #3455: ht-condor job runner crash with docker universe
```
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "/galaxy-central/lib/galaxy/jobs/runners/condor.py", line 69, in queue_job
    container = self.find_container( job_wrapper )
AttributeError: 'CondorJobRunner' object has no attribute 'find_container'
```

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/condor.py#L69

ping @abdulrahmanazab

### PR DESCRIPTION
**Pull request by bgruening**
fixes https://github.com/galaxyproject/galaxy/issues/3455

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
@bgruening This was broken since it was introduced in https://github.com/galaxyproject/galaxy/pull/2278, are you sure you don't want to target 16.07 or 16.10?

**Comment by jmchilton** [comment]
Sorry about introducing the bug @bgruening - I'll support back porting the fix as far as you'd like - let me know.

**Comment by bgruening** [comment]
No need to be sorry. Feel free to backport it to 16.10 if you like. One stupid question, howto re-target a PR? Do I need to close it and do a new one?

**Comment by nsoranzo** [comment]
If it's not merged yet, you should be able to change the target branch by clicking the "Edit" button near the PR title.

**Comment by bgruening** [comment]
Oh, I thought this is just for the title, thanks!
